# ===================================================================================
# Arquivo: gradle/libs.versions.toml
# Descrição: Catálogo centralizado de versões, bibliotecas e plugins para o Catfeina.
# ===================================================================================

[versions]

kotlin = "2.2.20"
compose-multiplatform = "1.9.0"
agp = "8.13.0"
androidx-activityCompose = "1.11.0"
composeHotReload = "1.0.0-rc02"
kermit = "2.0.8"
kotlinx-coroutines = "1.10.2"
ktor = "3.3.1"
precompose = "1.6.2"
kotlinx-serialization = "1.9.0"
metro = "0.6.10"
sketch = "4.3.1"
multiplatformSettings = "1.3.0"
kotlinx-datetime = "0.7.1-0.6.x-compat"
sqlDelight = "2.1.0"
buildKonfig = "0.17.1"
materialKolor = "3.0.1"
ksp = "2.2.20-2.0.4"
composeBom = "2025.10.00"
lifecycle = "2.9.4"

# se mudar a versão, atualizar no settings.gradle.kts
foojay-resolver-convention = "1.0.0"


[libraries]

androidx-activityCompose = { module = "androidx.activity:activity-compose", version.ref = "androidx-activityCompose" }
kermit = { module = "co.touchlab:kermit", version.ref = "kermit" }
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinx-coroutines" }
kotlinx-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "kotlinx-coroutines" }
kotlinx-coroutines-swing = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-swing", version.ref = "kotlinx-coroutines" }
kotlinx-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "kotlinx-coroutines" }
ktor-client-core = { module = "io.ktor:ktor-client-core", version.ref = "ktor" }
ktor-client-content-negotiation = { module = "io.ktor:ktor-client-content-negotiation", version.ref = "ktor" }
ktor-serialization-json = { module = "io.ktor:ktor-serialization-kotlinx-json", version.ref = "ktor" }
ktor-client-logging = { module = "io.ktor:ktor-client-logging", version.ref = "ktor" }
ktor-client-darwin = { module = "io.ktor:ktor-client-darwin", version.ref = "ktor" }
ktor-client-okhttp = { module = "io.ktor:ktor-client-okhttp", version.ref = "ktor" }
ktor-client-js = { module = "io.ktor:ktor-client-js", version.ref = "ktor" }
precompose = { module = "moe.tlaster:precompose", version.ref = "precompose" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinx-serialization" }
sketch = { module = "io.github.panpf.sketch4:sketch-compose", version.ref = "sketch" }
sketchHttp = { module = "io.github.panpf.sketch4:sketch-http", version.ref = "sketch" }
multiplatformSettings = { module = "com.russhwolf:multiplatform-settings-no-arg", version.ref = "multiplatformSettings" }
kotlinx-datetime = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version.ref = "kotlinx-datetime" }
sqlDelight-driver-sqlite = { module = "app.cash.sqldelight:sqlite-driver", version.ref = "sqlDelight" }
sqlDelight-driver-android = { module = "app.cash.sqldelight:android-driver", version.ref = "sqlDelight" }
sqlDelight-driver-native = { module = "app.cash.sqldelight:native-driver", version.ref = "sqlDelight" }
sqlDelight-driver-js = { module = "app.cash.sqldelight:web-worker-driver", version.ref = "sqlDelight" }
materialKolor = { module = "com.materialkolor:material-kolor", version.ref = "materialKolor" }
androidx-lifecycle-runtime-ktx = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "lifecycle" }
androidx-lifecycle-viewmodel-compose = { module = "androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "lifecycle" }
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
androidx-compose-ui = { group = "androidx.compose.ui", name = "ui" }
androidx-compose-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
androidx-compose-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
androidx-compose-material3 = { group = "androidx.compose.material3", name = "material3" }
androidx-compose-material-icons-extended = { group = "androidx.compose.material", name = "material-icons-extended" }
androidx-compose-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }


[plugins]

kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
compose-multiplatform = { id = "org.jetbrains.compose", version.ref = "compose-multiplatform" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
android-application = { id = "com.android.application", version.ref = "agp" }
android-kmp-library = { id = "com.android.kotlin.multiplatform.library", version.ref = "agp" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
composeHotReload = { id = "org.jetbrains.compose.hot-reload", version.ref = "composeHotReload" }
kotlinx-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
metro = { id = "dev.zacsweers.metro", version.ref = "metro" }
sqlDelight = { id = "app.cash.sqldelight", version.ref = "sqlDelight" }
buildKonfig = { id = "com.codingfeline.buildkonfig", version.ref = "buildKonfig" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
foojay-resolver-convention = { id = "org.gradle.toolchains.foojay-resolver-convention", version.ref = "foojay-resolver-convention" }


[bundles]

# Dependências comuns para multiplataforma (usado em commonMain)
commons = [
    "kermit",
    "kotlinx-coroutines-core",
    "ktor-client-core",
    "ktor-client-content-negotiation",
    "ktor-serialization-json",
    "ktor-client-logging",
    "precompose",
    "kotlinx-serialization-json",
    "sketch",
    "sketchHttp",
    "multiplatformSettings",
    "kotlinx-datetime",
    "materialKolor",
]

# Dependências da UI do Jetpack Compose (usado no androidMain e desktopMain)
compose = [
    "androidx-compose-ui",
    "androidx-compose-ui-graphics",
    "androidx-compose-ui-tooling-preview",
    "androidx-compose-material3",
    "androidx-compose-material-icons-extended",
]

# Dependências específicas para a plataforma Android (usado no androidMain)
android = [
    "kotlinx-coroutines-android",
    "ktor-client-okhttp",
    "sqlDelight-driver-android",
    "androidx-activityCompose",
    "androidx-lifecycle-runtime-ktx",
    "androidx-lifecycle-viewmodel-compose",
]

# Dependências específicas para a plataforma Desktop/JVM (usado no desktopMain)
desktop = [
    "kotlinx-coroutines-swing",
    "ktor-client-okhttp",
    "sqlDelight-driver-sqlite",
]

# Dependências específicas para a plataforma iOS (usado no iosMain)
ios = [
    "ktor-client-darwin",
    "sqlDelight-driver-native",
]

# Dependências específicas para a plataforma JavaScript (usado no jsMain)
js = [
    "ktor-client-js",
    "sqlDelight-driver-js",
]